### ISSUE TITLE
Ded Server Needs Debugging

### ISSUE THREAD

**Issue by edgaradr223** [KenyMylankca/HarshenUniverse#27]
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: java.lang.NullPointerException
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at kenijey.harshenuniverse.base.BaseConfig.get(BaseConfig.java:68)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at kenijey.harshenuniverse.base.BaseConfig.get(BaseConfig.java:61)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at kenijey.harshenuniverse.config.AccessoryConfig.get(AccessoryConfig.java:40)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at kenijey.harshenuniverse.config.AccessoryConfig.read(AccessoryConfig.java:33)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at kenijey.harshenuniverse.base.BaseConfig.syncConfig(BaseConfig.java:48)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at kenijey.harshenuniverse.base.BaseConfig.preInit(BaseConfig.java:42)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at kenijey.harshenuniverse.proxy.CommonProxy.preInit(CommonProxy.java:98)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at kenijey.harshenuniverse.HarshenUniverse.preInit(HarshenUniverse.java:56)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at java.lang.reflect.Method.invoke(Unknown Source)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at java.lang.reflect.Method.invoke(Unknown Source)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at java.lang.reflect.Method.invoke(Unknown Source)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at java.lang.reflect.Method.invoke(Unknown Source)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> [01:23:46] [Client thread/INFO] [STDERR]: [kenijey.harshenuniverse.base.BaseConfig:get:82]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> [01:23:46] [Client thread/INFO] [harshenuniverse]: HarshenUniverse loaded correctly

**Comment by KenyMylankca** [comment]
the mod needs to be updated... but there is nobody can do it effectively xD i dunno... time will tell something. sorry

**Comment by KenyMylankca** [comment]
looks like you removed the configs or something like that while starting the server, not the mods fault
