### ISSUE TITLE
Fell from a high distance and got this crash. Cannot load world.

### ISSUE THREAD

**Issue by metocolipson1** [KenyMylankca/HarshenUniverse#81]
Self explanatory title, not sure what else to tell you.
[crash-2020-10-23_13.52.34-server.txt](https://github.com/KenyMylankca/HarshenUniverse/files/5431031/crash-2020-10-23_13.52.34-server.txt)
EDIT: Used a backup of the world. I just recently started getting this crash consistently while walking around the world with your newest version of the mod.

**Comment by KenyMylankca** [comment]
yeah i know. it's fixed in https://github.com/KenyMylankca/HarshenUniverse/commit/2709cd3f6acebc89bf5017b84ca6b4b61cb0f1b7. please wait for the next release. thanks for reporting!
