### ISSUE TITLE
A crash report

### ISSUE THREAD

**Issue by CloudMeow** [KenyMylankca/HarshenUniverse#92]
I am making a modpack . but when I enter the dimension of Pontus，my game crash.
[crash-2020-11-28_18.12.05-server.txt](https://github.com/KenyMylankca/HarshenUniverse/files/5610528/crash-2020-11-28_18.12.05-server.txt)

**Comment by KenyMylankca** [comment]
report to electroblob wizardy mod

**Comment by CloudMeow** [comment]
Okay，I got a answer about it. But there are many monsters(from many different mods) spawn everywhere in Pontus. It is so messy and inconsequent. I set the whitelist is overword，but they still spawn in Pontus.

**Comment by KenyMylankca** [comment]
it's still not Harshen Universe's problem. Because all the H.U. done is adding a fucking dimension(world) and i dont really know why other mods messing it.
