### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by lartts** [KenyMylankca/HarshenUniverse#94]
Crash Log:
[latest.log](https://github.com/KenyMylankca/HarshenUniverse/files/6094730/latest.log)

Crash Report:
[crash-2021-02-12_21.26.35-server.txt](https://github.com/KenyMylankca/HarshenUniverse/files/6094729/crash-2021-02-12_21.26.35-server.txt)

**Comment by KenyMylankca** [comment]
when did it happen?(while doing what) 
did it happen once only or more than once?
does it still happen?
